debug: false
use-redis-bungee: false
api:
  host: "http://127.0.0.1:8080"
  key: "YOUR_API_KEY"
database:
  type: "MYSQL" #MYSQL | SQLITE
  user: "root"
  password: "root"
  url: "jdbc:mysql://localhost:3306/dbname"
storage:
  type: "REDIS" #YAML | REDIS
  url: "redis://user:password@localhost:6379/0"
settings:
  disable-servers:
    - "server1"
  disable-nicks:
    - "Klayzx"
messages:
  save-messages: true
  save-commands: true
  commands:
    - "msg"
    - "m"
    - "r"
    - "reply"

commands:
  chat-report:
    enabled: true
    command: "chatreport"
    usage: "/chatreport (playerName)"
    permission: "pandoracrp.command.chatreport"
    aliases:
      - "crp"
  report:
    enabled: true
    command: "report"
    usage: "/report (playerName)"
    permission: "pandoracrp.command.report"
    aliases:
      - "repo"

report:
  cooldown: 15 # In seconds
  max-reason-chars: 36
  messages:
    sent-to:
      staffs:
        - "&r "
        - "&c&l¡NEW REPORT!"
        - "&r "
        - "&fSender: &6%reporter%"
        - "&fTarget: &6%target%"
        - "&fReason: &6%reason%"
        - "&fServer: &6%server%"
        - "&r "
        - "text: &6&o(Click here to go) hover:&7Click here to go to the server. action:RUN_COMMAND:/server %server%"
  header: |-
    &e&lSelect an option:
    &e
  options:
    - ==: ReportOption
      text: '&8   ► &b&nHacks'
      hover: '&7Report %target% for hacks'
      command: '/report %target% Hacks'
    - ==: ReportOption
      text: '&8   ► &b&nChat infraction'
      hover: '&7Report %target% for chat infractions'
      command: '/chatreport %target%'

