debug: false
use-redis-bungee: false
api:
  host: "http://127.0.0.1:8080"
  key: ""
database:
  type: "MYSQL" #MYSQL
  user: "root"
  password: "root"
  url: "jdbc:mysql://localhost:3306/dbname"
storage:
  type: REDIS #YAML | REDIS | DISABLED
  ssl: false
  url: "redis://user:password@localhost:6379/0"

messages:
  save-commands: true
  commands:
    - "msg"
    - "m"
    - "r"
    - "reply"

commands:
  chat-report:
    command: "chatreport"
    usage: "/chatreport (playerName)"
    permission: "pandoracrp.command.chatreport"
    aliases:
      - "crp"
  report:
    command: "report"
    usage: "/report (playerName)"
    permission: "pandoracrp.command.report"
    aliases:
      - "repo"

report:
  cooldown: 15 # In seconds
  messages:
    sent-to:
      success:
        - "&aYou have successfully reported %target% Reason: %reason%"
      staffs:
        - "&r "
        - "&c&l¡NEW REPORT!"
        - "&r "
        - "&fSender: &6%reporter%"
        - "&fTarget: &6%target%"
        - "&fReason: &6%reason%"
        - "&fServer: &6%server%"
        - "&r "
    server-component:
      text: "&6&o(Click here to go)"
      hover: "&7Click here to go to the server."
      command: "/server %server%"
  header: |-
    &e&lSelect an option:
    &e
  options:
    - text: '&8   ► &b&nHacks'
      hover: '&7Report %target% for hacks'
      command: '/report %target% Hacks'
    - text: '&8   ► &b&nChat infraction'
      hover: '&7Report %target% for chat infractions'
      command: '/chatreport %target%'
